Repository PJA-ProJect-Assistant/pja_backend, pull requests merged in 2025-07, with the labels that each got.

#330 [Refactor] erd ai 생성 요청 코드 리팩토링
  PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
Labels: 🔨 Refactor

#334 [Fix] refresh token redis key이름 변경
  PJA/src/main/java/com/project/PJA/security/service/RefreshTokenService.java
Labels: 🐞 BugFix

#336 [Feat] 유사 워크스페이스 검색 권한 로직 수정
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature
