Repository PJA-ProJect-Assistant/pja_backend, pull requests merged in 2025-06, with the labels that each got.

#28 [Feat] 비밀번호 변경 기능 추가
  PJA/src/main/java/com/project/PJA/security/controller/AuthController.java
  PJA/src/main/java/com/project/PJA/security/jwt/JwtAuthenticationFilter.java
  PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
  PJA/src/main/java/com/project/PJA/user/dto/ChangePwRequestDto.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: ✨ Feature, 📬 API

#30 [Feat] 이메일 인증 후 비밀번호 찾기(변경) 기능 추가
  PJA/src/main/java/com/project/PJA/email/service/EmailService.java
  PJA/src/main/java/com/project/PJA/email/service/EmailServiceImpl.java
  PJA/src/main/java/com/project/PJA/security/service/EmailVerificationService.java
  PJA/src/main/java/com/project/PJA/user/controller/UserController.java
  PJA/src/main/java/com/project/PJA/user/dto/ChangePw2RequestDto.java
  PJA/src/main/java/com/project/PJA/user/dto/IdEmailRequestDto.java
  PJA/src/main/java/com/project/PJA/user/dto/VerifyEmailRequestDto.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: ✨ Feature, 📬 API

#32 [Feat] 워크스페이스 기능 추가
  PJA/build.gradle
  PJA/src/main/java/com/project/PJA/exception/ConflictException.java
  PJA/src/main/java/com/project/PJA/exception/GlobalExceptionHandler.java
  PJA/src/main/java/com/project/PJA/invitation/controller/InvitationController.java
  PJA/src/main/java/com/project/PJA/invitation/dto/InvitationDecisionResponse.java
  PJA/src/main/java/com/project/PJA/invitation/dto/InvitationInfoResponse.java
  PJA/src/main/java/com/project/PJA/invitation/entity/Invitation.java
  PJA/src/main/java/com/project/PJA/invitation/enumeration/InvitationStatus.java
  PJA/src/main/java/com/project/PJA/invitation/repository/InvitationRepository.java
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceCreateRequest.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteRequest.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteResponse.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceProgressStep.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceResponse.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceUpdateRequest.java
  PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
  PJA/src/main/java/com/project/PJA/workspace/entity/WorkspaceMember.java
  PJA/src/main/java/com/project/PJA/workspace/enumeration/ProgressStep.java
  PJA/src/main/java/com/project/PJA/workspace/enumeration/WorkspaceRole.java
  PJA/src/main/java/com/project/PJA/workspace/repository/WorkspaceMemberRepository.java
  PJA/src/main/java/com/project/PJA/workspace/repository/WorkspaceRepository.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature, 🔨 Refactor

#33 [Feat] 프로필 이미지 업데이트/삭제/조회 기능 추가
  PJA/.gitignore
  PJA/docker-compose.yml
  PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
  PJA/src/main/java/com/project/PJA/common/file/FileStorageService.java
  PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: ✨ Feature, 📬 API

#35 [Refactor] 회원 관리 코드 전반 리팩토링
  PJA/src/main/java/com/project/PJA/security/controller/AuthController.java
  PJA/src/main/java/com/project/PJA/user/controller/UserController.java
  PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: 🔨 Refactor

#38 [Feat] 워크스페이스 오너/멤버 권한 검증 메서드 추가
  PJA/src/main/java/com/project/PJA/workspace/repository/WorkspaceMemberRepository.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#40 [Feat] 아이디어 요약 기능 생성
  PJA/build.gradle
  PJA/src/main/java/com/project/PJA/common/config/RestTemplateConfig.java
  PJA/src/main/java/com/project/PJA/idea/controller/IdeaController.java
  PJA/src/main/java/com/project/PJA/idea/dto/AiProblemSolving.java
  PJA/src/main/java/com/project/PJA/idea/dto/AiProjectSummaryResponse.java
  PJA/src/main/java/com/project/PJA/idea/dto/ProblemSolving.java
  PJA/src/main/java/com/project/PJA/idea/dto/ProjectInfoRequest.java
  PJA/src/main/java/com/project/PJA/idea/dto/ProjectSummaryReponse.java
  PJA/src/main/java/com/project/PJA/idea/dto/ProjectSummaryRequest.java
  PJA/src/main/java/com/project/PJA/idea/entity/Idea.java
  PJA/src/main/java/com/project/PJA/idea/repository/IdeaRepository.java
  PJA/src/main/java/com/project/PJA/idea/service/IdeaService.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceResponse.java
  PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
  PJA/src/main/java/com/project/PJA/workspace/repository/WorkspaceMemberRepository.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature, 📬 API

#45 [Feat] 요구사항 명세서 기능 생성
  PJA/src/main/java/com/project/PJA/idea/controller/IdeaController.java
  PJA/src/main/java/com/project/PJA/idea/service/IdeaService.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
  PJA/src/main/java/com/project/PJA/requirement/dto/RequirementContentRequest.java
  PJA/src/main/java/com/project/PJA/requirement/dto/RequirementRequest.java
  PJA/src/main/java/com/project/PJA/requirement/dto/RequirementResponse.java
  PJA/src/main/java/com/project/PJA/requirement/entity/Requirement.java
  PJA/src/main/java/com/project/PJA/requirement/enumeration/RequirementType.java
  PJA/src/main/java/com/project/PJA/requirement/repository/RequirementRepository.java
  PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
  PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
Labels: ✨ Feature, 📬 API

#47 fix: 병합 하면서 빠진 코드 수정
  PJA/src/main/java/com/project/PJA/erd/entity/ErdRelationShips.java
Labels: 🐞 BugFix

#49 [Feat] API 명세서 기능 추가
  PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
  PJA/src/main/java/com/project/PJA/api/dto/ApiRequest.java
  PJA/src/main/java/com/project/PJA/api/dto/ApiResponse.java
  PJA/src/main/java/com/project/PJA/api/dto/Data.java
  PJA/src/main/java/com/project/PJA/api/dto/Response.java
  PJA/src/main/java/com/project/PJA/api/entity/Api.java
  PJA/src/main/java/com/project/PJA/api/repository/ApiRepository.java
  PJA/src/main/java/com/project/PJA/api/service/ApiService.java
Labels: ✨ Feature

#61 [Fix] cors 설정 관련 프론트 도메인 수정
  PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
Labels: 🐞 BugFix

#65 [Fix] refresh token 토큰 생성 시의 만료 기간 변경
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/java/com/project/PJA/security/service/AuthUserService.java
Labels: 🐞 BugFix

#66 [Fix] getUsername 반환값 잘못된거 수정
  PJA/src/main/java/com/project/PJA/user/entity/Users.java
Labels: 🐞 BugFix

#74 [Chore] elastic search 환경 설정
  PJA/.gitignore
  PJA/build.gradle
  PJA/docker-compose.yml
  PJA/logstash.conf
  PJA/src/main/resources/logback.xml
Labels: ⚙ Setting

#77 [Fix] JWT Secret Key 인코딩 방식 지정
  PJA/.gitignore
  PJA/build.gradle
  PJA/docker-compose.yml
  PJA/logstash.conf
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceUpdateRequest.java
  PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
  PJA/src/main/resources/application.properties
  PJA/src/main/resources/logback.xml
Labels: 🐞 BugFix

#78 [Fix] 에러 로그 추가 및 jwt_secret key 설정 강화
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/resources/application.properties
Labels: 🐞 BugFix

#83 [Chore] 자잘한 설정 변경
  PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
  PJA/src/main/java/com/project/PJA/erd/controller/ErdColumnController.java
  PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
  PJA/src/main/java/com/project/PJA/erd/controller/ErdRelationController.java
  PJA/src/main/java/com/project/PJA/erd/controller/ErdTableController.java
  PJA/src/main/java/com/project/PJA/idea/controller/IdeaController.java
  PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
  PJA/src/main/java/com/project/PJA/member/controller/MemberController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureCategoryController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
Labels: 🔨 Refactor

#84 [Refactor] 아이디어 요약에서 프로젝트 정보로 변경
  PJA/src/main/java/com/project/PJA/idea/controller/IdeaController.java
  PJA/src/main/java/com/project/PJA/idea/dto/ProjectInfoRequest.java
  PJA/src/main/java/com/project/PJA/idea/repository/IdeaRepository.java
  PJA/src/main/java/com/project/PJA/idea/service/IdeaService.java
  PJA/src/main/java/com/project/PJA/invitation/controller/InvitationController.java
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/MlProblemSolving.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/MlProjectInfoResponse.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProblemSolving.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoRequest.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoResponse.java
  PJA/src/main/java/com/project/PJA/projectinfo/entity/ProjectInfo.java
  PJA/src/main/java/com/project/PJA/projectinfo/repository/ProjectInfoRepository.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
Labels: 🔨 Refactor

#85 [Refactor] AI 요청 기능 개선 및 저장 로직 추가
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProblemSolvingData.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoCreateRequest.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoCreateResponse.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoData.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoWrapper.java
  PJA/src/main/java/com/project/PJA/projectinfo/repository/ProjectInfoRepository.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
  PJA/src/main/java/com/project/PJA/requirement/dto/RequirementRecommendationRequest.java
  PJA/src/main/java/com/project/PJA/requirement/dto/RequirementRecommendationResponse.java
  PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteRequest.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteResponse.java
Labels: ✨ Feature, 🔨 Refactor

#86 [Feat] 사용자 행동 로그 수집 기본 설정
  PJA/.gitignore
  PJA/build.gradle
  PJA/docker-compose.yml
  PJA/logstash.conf
  PJA/src/main/java/com/project/PJA/common/config/JacksonConfig.java
  PJA/src/main/java/com/project/PJA/common/user_act_log/UserActionLog.java
  PJA/src/main/java/com/project/PJA/common/user_act_log/UserActionLogService.java
  PJA/src/main/java/com/project/PJA/common/user_act_log/UserActionType.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/resources/logback.xml
Labels: ⚙ Setting, ✨ Feature

#87 [Feat] 사용자 행동 로그 수집 - 요구사항, 액션, 액션 게시글, 액션 댓글
  PJA/src/main/java/com/project/PJA/common/user_act_log/UserActionType.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
Labels: ✨ Feature

#88 [Fix] email nullable 설정
  PJA/src/main/java/com/project/PJA/user/entity/Users.java
Labels: 🐞 BugFix

#91 [Chore] CI/CD 설정
  .github/workflows/deploy.yml
Labels: ⚙ Setting

#94 [Fix] Gradlew 실행 권한 설정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix

#101 [Refactor] 사용자 행동 로그 리팩토링
  PJA/src/main/java/com/project/PJA/notification/controller/NotificationController.java
  PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
  PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
  PJA/src/main/java/com/project/PJA/notification/entity/UserNotification.java
  PJA/src/main/java/com/project/PJA/notification/repository/NotificationRepository.java
  PJA/src/main/java/com/project/PJA/notification/repository/UserNotificationRepository.java
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
Labels: 🔨 Refactor

#102 [Refactor] 사용자 행동 로그 리팩토링
  PJA/src/main/java/com/project/PJA/common/user_act_log/UserActionType.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
Labels: 🔨 Refactor

#104 [Fix] 회원가입 DTO로 인한 에러 해결
  PJA/src/main/java/com/project/PJA/user/controller/UserController.java
  PJA/src/main/java/com/project/PJA/user/dto/SignupDto.java
Labels: 🐞 BugFix

#112 [Fix] Workspace 삭제 시 FeatureCategory 외래키 제약조건 위반 문제 해결
  PJA/src/main/java/com/project/PJA/project_progress/entity/FeatureCategory.java
Labels: 🐞 BugFix

#114 [Feat] Action ai 추천받기 기능
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/ActionAiRecommendedResponse.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/ActionAiRequestDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/ActionData.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/ActionRecommendationJson.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/CategoryData.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/FeatureData.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/aiDto/RecommendedAction.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: ✨ Feature, 📬 API

#118 [Fix] erd 중복 생성 에러 해결
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
Labels: 🐞 BugFix

#119 [Feat] 메인 기능, 기술 스택 삭제 기능 추가
  PJA/.gitignore
  PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
  PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#121 [Fix] 초대 메일 텍스트에서 링크로 수정
  PJA/src/main/java/com/project/PJA/email/service/EmailServiceImpl.java
  PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
Labels: 🐞 BugFix

#122 [Fix & Refactor] 프로젝트 진행 관련 삭제 문제 해결 및 카테고라&기능 상태 Boolean으로 변경
  PJA/src/main/java/com/project/PJA/erd/entity/ErdTable.java
  PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
  PJA/src/main/java/com/project/PJA/notification/entity/UserNotification.java
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureCategoryController.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/CreateCategoryAndFeatureDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/FeatureCategoryResponseDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/FeatureResponseDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/UpdateActionDto.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/UpdateFeatureAndCategoryDto.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/Action.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/ActionComment.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/ActionParticipant.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/ActionPost.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/ActionPostFile.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/Feature.java
  PJA/src/main/java/com/project/PJA/project_progress/entity/FeatureCategory.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/FeatureCategoryService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/FeatureService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java
Labels: 🐞 BugFix, 🔨 Refactor

#125 [Feat & Refactor] 프로젝트 진행 페이지 관련 기능 수정 및 리팩토링
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/FeatureCategoryRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/FeatureRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java
Labels: ✨ Feature, 🔨 Refactor

#129 [Fix] erd ai 생성 요청 에러 해결
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
Labels: 🐞 BugFix

#130 [Fix] 사용자 이름 변경에러 해결
  PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
  PJA/src/main/java/com/project/PJA/user/dto/ChangeNameRequestDto.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: 🐞 BugFix

#131 [Fix] 카테고리 test 여부 수정 안되는거 수정_ver1
  PJA/src/main/java/com/project/PJA/project_progress/service/FeatureCategoryService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/FeatureService.java
Labels: 🐞 BugFix

#135 [Feat] 깃 연동 기능 추가
  PJA/src/main/java/com/project/PJA/git_interlocking/controller/GitInterlockingController.java
  PJA/src/main/java/com/project/PJA/git_interlocking/dto/GitInfoDto.java
  PJA/src/main/java/com/project/PJA/git_interlocking/entity/GitInterlocking.java
  PJA/src/main/java/com/project/PJA/git_interlocking/repository/GitInterlockingRepository.java
  PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
Labels: ✨ Feature

#142 [Fix] erd id 두 번 생성 에러 수정
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
Labels: 🐞 BugFix

#145 [Feat] AI 추천 조건에 단계 및 요구사항 개수 제한 추가
  PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
Labels: ✨ Feature

#147 [Fix] erd모델 수정
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: 🐞 BugFix

#148 [Feat] erd ai 생성 관계도 db에 넣기 추가
  PJA/src/main/java/com/project/PJA/erd/repository/ErdColumnRepository.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
Labels: ✨ Feature

#149 [Feat] 프로젝트 진행 액션 상태 종류 추가
  PJA/src/main/java/com/project/PJA/project_progress/entity/Progress.java
Labels: ✨ Feature

#151 [Feature] 최근 활동 기능 개발
  PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
  PJA/src/main/java/com/project/PJA/api/service/ApiService.java
  PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
  PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
  PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
  PJA/src/main/java/com/project/PJA/invitation/controller/InvitationController.java
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
  PJA/src/main/java/com/project/PJA/member/controller/MemberController.java
  PJA/src/main/java/com/project/PJA/member/service/MemberService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
  PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
  PJA/src/main/java/com/project/PJA/workspace_activity/controller/WorkspaceActivityController.java
  PJA/src/main/java/com/project/PJA/workspace_activity/dto/WorkspaceActivityResponseDto.java
  PJA/src/main/java/com/project/PJA/workspace_activity/entity/WorkspaceActivity.java
  PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityActionType.java
  PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityTargetType.java
  PJA/src/main/java/com/project/PJA/workspace_activity/repository/WorkspaceActivityRepository.java
  PJA/src/main/java/com/project/PJA/workspace_activity/service/WorkspaceActivityService.java
Labels: ✨ Feature

#156 [Feat] 요구사항 명세서 AI 추천 요청시 글 길이 유효성 검사 로직 추가
  PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature, 🔨 Refactor

#162 [Feat] SSE 기능 추가
  PJA/src/main/java/com/project/PJA/notification/controller/NotificationController.java
  PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
  PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
  PJA/src/main/java/com/project/PJA/sse/repository/SseEmitterRepository.java
Labels: ✨ Feature

#163 [Refactor] sse 컨트롤러 반환값 수정
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
Labels: 🔨 Refactor

#164 [Refactor] sse 연결 반환 타입 원래대로 수정
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
Labels: 🔨 Refactor

#165 [Feat] 대시보드 통계 기능 개발
  PJA/src/main/java/com/project/PJA/actionAnalysis/controller/ActionAnalysisController.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AvgProcessingTimeGraphDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceGraphDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/entity/AvgProcessingTimeResult.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/entity/TaskImbalanceResult.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/repository/AvgProcessingTimeResultRepository.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisSaveService.java
  PJA/src/main/java/com/project/PJA/user_act_log/dto/UserActionLogParsing.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/LogSchedular.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/UserActionLogService.java
Labels: ✨ Feature

#167 [Feat] workspaceMember에 profile 추가
  PJA/src/main/java/com/project/PJA/member/dto/MemberResponse.java
  PJA/src/main/java/com/project/PJA/member/service/MemberService.java
Labels: ✨ Feature

#169 [Feat] sse 알림 구독 토큰 직접 받아서 user 정보 가져오게 수정
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
Labels: ✨ Feature

#170 [Chore] 모든 메서드 허용하도록 수정
  PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
Labels: ⚙ Setting

#173 [Refactor] 오류 수정
  PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
Labels: 🔨 Refactor

#176 [Feat] 깃허브 url 조회 기능 수정
  PJA/src/main/java/com/project/PJA/git_interlocking/controller/GitInterlockingController.java
  PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
  PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
Labels: ✨ Feature

#177 [Feat] 진행중인 내 작업(action) 조회하기 기능 추가
  PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/MyActionDto.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: ✨ Feature

#178 [Feat] 내 진행률 불러오기 기능 추가 및 현재 진행중인 작업 리스트 불러오기 수정
  PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/MyActionDto.java
  PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: ✨ Feature

#179 [Refactor] erd ai 생성, 조회, 테이블, 컬럼 관련 리팩토링
  PJA/src/main/java/com/project/PJA/erd/controller/ErdColumnController.java
  PJA/src/main/java/com/project/PJA/erd/controller/ErdTableController.java
  PJA/src/main/java/com/project/PJA/erd/dto/ErdColumnResponseDto.java
  PJA/src/main/java/com/project/PJA/erd/dto/ErdTableResponseDto.java
  PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/FieldDto.java
  PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/TableNodeDto.java
  PJA/src/main/java/com/project/PJA/erd/entity/ErdTable.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdColumnService.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdRelationService.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdTableService.java
  PJA/src/main/java/com/project/PJA/erd/service/ReactFlowConverter.java
Labels: 🔨 Refactor

#180 [Refactor] erd relationships 리팩토링
  PJA/src/main/java/com/project/PJA/erd/controller/ErdRelationController.java
  PJA/src/main/java/com/project/PJA/erd/dto/CreateErdRelationDto.java
  PJA/src/main/java/com/project/PJA/erd/dto/ErdRelationResponseDto.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdRelationService.java
Labels: 🔨 Refactor

#182 [Fix] json 파싱 시 이름 매칭 문제 해결
  PJA/src/main/java/com/project/PJA/user_act_log/dto/DetailsParticipants.java
Labels: 🐞 BugFix

#183 [Refactor] 담당자 불균형 그래프 응답 데이터 추가
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceGraphDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java
Labels: 🔨 Refactor

#184 [Feat] 워크스페이스 내의 최근활동 조회 기능 추가
  PJA/src/main/java/com/project/PJA/api/service/ApiService.java
  PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
  PJA/src/main/java/com/project/PJA/workspace_activity/dto/WorkspaceActivityResponseDto.java
  PJA/src/main/java/com/project/PJA/workspace_activity/entity/WorkspaceActivity.java
  PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityActionType.java
  PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityTargetType.java
  PJA/src/main/java/com/project/PJA/workspace_activity/service/WorkspaceActivityService.java
Labels: ✨ Feature

#188 [Fix] 회원 탈퇴 시 이메일 nullable로 인한 문제 해결
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: 🐞 BugFix

#190 [Feat] API 명세서 AI 자동 생성 워크스페이스 진행도 검사 로직 추가
  PJA/src/main/java/com/project/PJA/api/service/ApiService.java
Labels: ✨ Feature

#193 [Fix] s3 bucket 이름 잘못된거 수정
  PJA/src/main/resources/application.properties
Labels: 🐞 BugFix

#194 [Refactor] PutObjectRequest에서 .acl() 제거
  PJA/src/main/java/com/project/PJA/common/service/S3Service.java
Labels: 🔨 Refactor

#195 [Refactor] 프로필 이미지 변경에 save 추가
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: 🔨 Refactor

#196 [Feat] 프로필 이미지 삭제 및 액션 포스트 파일 업데이트 추가
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
  PJA/src/main/java/com/project/PJA/user/service/UserService.java
Labels: ✨ Feature

#200 [Feat] public인 워크스페이스의 프로젝트 정보 전체 조회 기능 추가
  PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
  PJA/src/main/java/com/project/PJA/projectinfo/repository/ProjectInfoRepository.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/security/config/SecurityConfig.java
  PJA/src/main/java/com/project/PJA/workspace/repository/WorkspaceRepository.java
Labels: ✨ Feature

#201 [Refactor] 평균 작업 처리 시간 반환 데이터 수정
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AvgProcessingTimeGraphDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java
Labels: 🔨 Refactor

#206 [Feat] 유사한 워크스페이스 검색 기능 추가
  PJA/src/main/java/com/project/PJA/projectinfo/dto/PublicProjectInfoResponse.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceIds.java
  PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceRequest.java
  PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceResponse.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#210 [Refactor] 유사한 워크스페이스 post에서 get으로 수정, 워크스페이스 아이디에서 프로젝트 아이디로 이름 수정
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceIds.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: 🔨 Refactor

#211 [Feat] 토큰에서 userId 추출 -> uid 추출
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
Labels: ✨ Feature

#213 [Fix] 커넥션 풀 사이즈 문제 관련 설정
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
  PJA/src/main/resources/application.properties
Labels: 🐞 BugFix

#214 [Fix] 커넥션 풀 사이즈 문제 관련 설정
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
  PJA/src/main/resources/application.properties
Labels: 🐞 BugFix

#216 [Chore] webconfig에 프론트 도메인 추가
  PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
Labels: ⚙ Setting

#221 [Feat] 프로젝트 진행 초반 AI 생성 내용 DB에 저장
  PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java
Labels: ✨ Feature

#222 [Refactor] 초대 이메일 링크 수정
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
Labels: 🔨 Refactor

#228 [Fix] createActionDto 수정으로 인했던 에러 해결_ver2
  PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: 🐞 BugFix

#229 [Feat] 실시간 수정 방지 Redis 락
  PJA/src/main/java/com/project/PJA/common/component/RedisLockManager.java
  PJA/src/main/java/com/project/PJA/editing/controller/EditingController.java
  PJA/src/main/java/com/project/PJA/editing/dto/EditingRequest.java
  PJA/src/main/java/com/project/PJA/editing/dto/EditingResponse.java
  PJA/src/main/java/com/project/PJA/editing/dto/EditingUser.java
  PJA/src/main/java/com/project/PJA/editing/service/EditingService.java
  PJA/src/main/java/com/project/PJA/exception/GlobalExceptionHandler.java
  PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
  PJA/src/main/java/com/project/PJA/member/service/MemberService.java
  PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoData.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceAuthCache.java
  PJA/src/main/java/com/project/PJA/workspace/enumeration/WorkspaceRole.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#234 [Fix] 액션 생성 시 프론트에서 넘겨주지 않는 값 처리
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: 🐞 BugFix

#235 [Feat] 워크스페이스 내 사용자 역할 조회
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceRoleResponse.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#241 [Feat] LocalDateTime 커스텀 파서 추가 및 적용
  PJA/src/main/java/com/project/PJA/common/service/FlexibleLocalDateTimeDeserializer.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java
Labels: ✨ Feature

#247 [Fix] 다른 사용자가 기존 사용자의 기록 덮어쓰는거 고치기
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisSaveService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/user_act_log/enumeration/UserActionType.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/UserActionLogService.java
Labels: 🐞 BugFix

#249 [Feat] 중요도 변경되었을 때 유저행동로그 분석
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/user_act_log/enumeration/UserActionType.java
Labels: ✨ Feature

#252 [Fix] 작업 불균형 그래프 방금 유저 행동 발생한 사람들에 대해서만 담당자 뜨는 문제 고침
  PJA/src/main/java/com/project/PJA/actionAnalysis/controller/ActionAnalysisController.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AssigneeDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceResponseDto.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java
Labels: 🐞 BugFix

#260 [Fix] 멤버 삭제할 때 오너도 삭제되는 문제 해결
  PJA/src/main/java/com/project/PJA/member/service/MemberService.java
Labels: 🐞 BugFix

#262 [Fix] 로그 일단 다 막아서 해결
  PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisSaveService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/UserActionLogService.java
Labels: 🐞 BugFix

#263 [Feat] 워크스페이스 진행도 완료 수정에 6에서 5로도 수정 기능 추가
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#265 [Fix] 유사한 워크스페이스 검색 시 본인 워크스페이스 제외
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: 🐞 BugFix

#268 [Feat] 통계 모델 수정된 버전에 맞춰서 로그 다시 찍기
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
  PJA/src/main/java/com/project/PJA/user_act_log/enumeration/UserActionType.java
  PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
Labels: ✨ Feature

#274 [Fix] 워크스페이스 최근활동의 유저 정보를 현재의 값으로 가져오게 수정
  PJA/src/main/java/com/project/PJA/workspace_activity/entity/WorkspaceActivity.java
  PJA/src/main/java/com/project/PJA/workspace_activity/service/WorkspaceActivityService.java
Labels: 🐞 BugFix

#281 [Feat] 액션 게시글 댓글 생성 시의 data에 commentId 추가
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
Labels: ✨ Feature

#283 [Fix] content null 허용하기
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
Labels: 🐞 BugFix

#285 [Fix] 액션 게시글 사진 첨부 시, 기존 사진 삭제되는 문제 해결
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
Labels: 🐞 BugFix

#288 [Fix] 기존 파일 삭제하게 했던거 복구
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
Labels: 🐞 BugFix

#294 [Feat] AI 생성 시 워크스페이스 진행도 자동 갱신 기능 추가
  PJA/src/main/java/com/project/PJA/api/repository/ApiRepository.java
  PJA/src/main/java/com/project/PJA/api/service/ApiService.java
  PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
  PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java
  PJA/src/main/java/com/project/PJA/projectinfo/repository/ProjectInfoRepository.java
  PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
  PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
  PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceProgressStep.java
  PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#299 [Fix] SSE 구독 시 커넥션 누수 방지 및 emitter 비동기 처리
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
Labels: 🐞 BugFix

#302 [Fix] 비동기 메서드 다른 클래스로 분리
  PJA/src/main/java/com/project/PJA/PjaApplication.java
  PJA/src/main/java/com/project/PJA/notification/service/NotiAsyncService.java
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
  PJA/src/main/java/com/project/PJA/sse/service/SendEmitterService.java
Labels: 🐞 BugFix

#304 [Fix] action 생성 시 startDate, endDate 빈 문자열 처리
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
Labels: 🐞 BugFix

#306 [Fix] 액션 포스트 파일 기존에 있던 파일 삭제되는 문제 해결
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
Labels: 🐞 BugFix

#307 [Fix] 삭제할 파일 타입 변경
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
Labels: 🐞 BugFix

#310 [Feat] 알림 받을 사람에 자기 자신 필터링
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
Labels: ✨ Feature

#313 [Fix] @Transactional이 붙은 서비스와 비동기 sse 서비스 분리
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/NotiFacadeDto.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
  PJA/src/main/java/com/project/PJA/project_progress/service/NotificationFacade.java
Labels: 🐞 BugFix

#315 [Fix] sse 인증구조 직접 token에서 userId 가져오는 방식으로 개선
  PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
  PJA/src/main/java/com/project/PJA/security/service/AuthUserService.java
  PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
  PJA/src/main/java/com/project/PJA/user/repository/UserRepository.java
Labels: 🐞 BugFix

#318 [Feat] 알림 조회 시 actionId 추가
  PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
  PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
Labels: ✨ Feature

#322 [Feat] actionPost 게시글 조회의 commentList에 author 여부값 추가
  PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
  PJA/src/main/java/com/project/PJA/project_progress/dto/ActionCommentResponseDto.java
  PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
Labels: ✨ Feature

#327 [Fix] erd 생성이랑 erd ai 생성 컨트롤러 합치기
  PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
Labels: 🐞 BugFix
